Repository Leets-Official/EatMate-FE, pull requests merged in 2025-01, with the labels that each got.

#7 #5 Feat: 회원가입 기능 구현
  src/assets/images/defaultprofile.svg
  src/assets/images/error_check.svg
  src/components/SignUp/BirthdayGenderStep.tsx
  src/components/SignUp/MbtiStep.tsx
  src/components/SignUp/NicknameStep.tsx
  src/components/SignUp/PhoneNumStep.tsx
  src/components/SignUp/PolicyAgreementStep.tsx
  src/components/SignUp/ProfileImgStep.tsx
  src/components/SignUp/SignupInput.tsx
  src/components/SignUp/StudentIdStep.tsx
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/styles.ts
  src/components/common/Error/InputErrorMessage.tsx
  src/components/common/Header/styles.ts
  src/components/common/Modal/ActionModal.stories.tsx
  src/components/common/Modal/ActionModal.tsx
  src/components/common/Modal/CardModal.tsx
  src/components/common/Modal/styles.ts
  src/constants/policyContents.ts
  src/hooks/use-input.ts
  src/hooks/useInputHandler.ts
  src/pages/SignUpPage/Intro.tsx
  src/pages/SignUpPage/PolicyDetails.tsx
  src/pages/SignUpPage/SignUp.tsx
  src/pages/SignUpPage/SignUpLayout.tsx
  src/recoil/atoms/userAtom.tsx
  src/routes/route.tsx
  src/styles/SignUp/IntroPage.styled.ts
  src/styles/SignUp/SignUp.styled.ts
  src/styles/theme.d.ts
  src/styles/theme.ts
  src/utils/validate-input.ts
Labels: ✨Feature, 🎨Design, ♻Refactor

#15 #8 Feat: 구글 로그인 구현
  package-lock.json
  package.json
  src/apis/auth/auth.ts
  src/apis/axiosInstance.ts
  src/components/SignUp/BirthdayGenderStep.tsx
  src/components/SignUp/ProfileImgStep.tsx
  src/components/SignUp/SignupInput.tsx
  src/components/SignUp/StudentIdStep.tsx
  src/components/common/Error/InputErrorMessage.tsx
  src/pages/SignUpPage/Intro.tsx
  src/pages/SignUpPage/LoginCallback.tsx
  src/recoil/atoms/userAtom.tsx
  src/routes/route.tsx
  src/utils/validate-input.ts
Labels: ✨Feature, 🔗API

#14 #10 Feat: 필터링 모달 생성
  .storybook/preview.tsx
  src/assets/images/ic_option_check.svg
  src/components/common/Button/styles.ts
  src/components/common/Modal/FilterModal.stories.tsx
  src/components/common/Modal/FilterModal.tsx
  src/components/common/RangeSlider.tsx
Labels: 🐞BugFix, ✨Feature, 🎨Design

#9 #6 Feat: 홈 UI 구현
  .github/ISSUE_TEMPLATE/bugfix.md
  .github/ISSUE_TEMPLATE/feature.md
  .github/pull_request_template.md
  package-lock.json
  package.json
  src/assets/images/EatMate_circle_logo.svg
  src/assets/images/delivery/ic_asian.svg
  src/assets/images/delivery/ic_chicken.svg
  src/assets/images/delivery/ic_china.svg
  src/assets/images/delivery/ic_dessert.svg
  src/assets/images/delivery/ic_hamburger.svg
  src/assets/images/delivery/ic_japan.svg
  src/assets/images/delivery/ic_korea.svg
  src/assets/images/delivery/ic_pig.svg
  src/assets/images/delivery/ic_pizza.svg
  src/assets/images/ic_arrow_bottom.svg
  src/assets/images/ic_arrow_right.svg
  src/assets/images/ic_default_sort.svg
  src/assets/images/ic_home.svg
  src/assets/images/ic_home_color.svg
  src/assets/images/ic_locate.svg
  src/assets/images/ic_navi_logo.svg
  src/assets/images/ic_navi_logo_color.svg
  src/assets/images/ic_people.svg
  src/assets/images/ic_people_color.svg
  src/assets/images/ic_person.svg
  src/assets/images/ic_plus.svg
  src/components/Home/DeliveryCategory.tsx
  src/components/Home/MeetingList.tsx
  src/components/Home/MeetingListItem.tsx
  src/components/common/BottomNavi.tsx
  src/components/common/FloatingPostButton.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Header/styles.ts
  src/components/common/SortingButton/SortingButton.stories.tsx
  src/components/common/SortingButton/SortingButton.tsx
  src/components/common/Tab/Tab.stories.tsx
  src/components/common/Tab/Tab.tsx
  src/pages/Home.tsx
  src/styles/CommonStyle.ts
  src/types/svg.d.ts
  vite.config.ts
Labels: ✨Feature, 🎨Design

#20 #12 Feat:모임 생성 UI 구현
  package-lock.json
  package.json
  src/assets/images/ic_backImg_default1.svg
  src/assets/images/ic_backImg_default2.svg
  src/assets/images/ic_checked_box.svg
  src/assets/images/ic_selectImg.svg
  src/assets/images/ic_unChecked_box.svg
  src/components/SignUp/BirthdayGenderStep.tsx
  src/components/SignUp/MbtiStep.tsx
  src/components/SignUp/NicknameStep.tsx
  src/components/SignUp/PhoneNumStep.tsx
  src/components/SignUp/StudentIdStep.tsx
  src/components/common/Button/styles.ts
  src/components/common/Error/InputErrorMessage.tsx
  src/components/common/Header/styles.ts
  src/components/common/Input/Input.tsx
  src/components/common/Input/InputErrorMessage.tsx
  src/components/common/Input/InputGuide.tsx
  src/components/common/Input/styles.ts
  src/components/event/BackgroundOption.tsx
  src/components/event/GenderOption.tsx
  src/components/event/MeetingTimeOption.tsx
  src/components/event/ParticipantOption.tsx
  src/components/event/TimePicker.tsx
  src/pages/event/DeliveryMeetingCreate.tsx
  src/pages/event/OfflineMeetingCreate.tsx
  src/pages/signup/Intro.tsx
  src/pages/signup/LoginCallback.tsx
  src/pages/signup/PolicyDetails.tsx
  src/pages/signup/SignUpLayout.tsx
  src/routes/route.tsx
  src/styles/CommonStyle.ts
  src/styles/SignUp/IntroPage.styled.ts
  src/styles/SignUp/SignUp.styled.ts
  src/styles/theme.ts
Labels: ✨Feature, 🎨Design

#19 #18 Design: 배달팟 카테고리 변경
  src/assets/images/delivery/ic_chicken.svg
  src/assets/images/delivery/ic_coffee.svg
  src/components/Home/DeliveryCategory.tsx
  src/components/common/Tab/Tab.tsx
Labels: ✨Feature, 🎨Design

#17 #16 Design: range slider 변경
  package-lock.json
  package.json
  src/components/common/Modal/FilterModal.stories.tsx
  src/components/common/RangeSlider.tsx
Labels: ✨Feature, 🎨Design

#28 #25 Chore : range slider 수정
  src/components/common/Modal/FilterModal.tsx
  src/components/common/RangeSlider.tsx
  src/components/event/ParticipantOption.tsx
Labels: ✨Feature, 🎨Design

#27 #26 Design: button 컴포넌트 스타일 추가
  src/components/common/Button/Button.stories.tsx
  src/components/common/Button/styles.ts
  src/styles/theme.ts
Labels: 🎨Design

#29 #24 Design: 홈 UI 수정
  src/assets/images/ic_beer_cover.svg
  src/assets/images/ic_clock.svg
  src/assets/images/ic_close.svg
  src/assets/images/ic_delivery_cover.svg
  src/assets/images/ic_meal_cover.svg
  src/assets/images/ic_posting_beer.svg
  src/assets/images/ic_posting_delivery.svg
  src/assets/images/ic_posting_meal.svg
  src/components/Home/DeliveryCategory.tsx
  src/components/Home/MeetingList.tsx
  src/components/Home/MeetingListItem.tsx
  src/components/common/FloatingPostButton.tsx
  src/components/common/Modal/FilterModal.stories.tsx
  src/components/common/Modal/FilterModal.tsx
  src/components/common/RangeSlider.tsx
  src/components/common/SortingButton/SortingButton.tsx
  src/pages/Home.tsx
Labels: ✨Feature, 🎨Design

#31 #22 Feat:밥술 모임 생성 api 연결
  package-lock.json
  package.json
  src/apis/auth/auth.ts
  src/apis/axiosInstance.ts
  src/apis/meetings/createOfflineMeeting.ts
  src/components/common/FloatingPostButton.tsx
  src/components/event/BackgroundOption.tsx
  src/components/event/GenderOption.tsx
  src/components/event/MeetingTimeOption.tsx
  src/components/event/ParticipantOption.tsx
  src/components/event/WheelPicker.tsx
  src/hooks/useInputHandler.ts
  src/hooks/useUserGender.ts
  src/pages/event/OfflineMeetingCreate.tsx
  src/pages/signup/LoginCallback.tsx
  src/types/svg.d.ts
Labels: 🙋‍♀️Question, ✨Feature, 🔗API

#35 #30 Refactor:모임 생성 관련 리팩토링 + axios interceptor 에러 핸들링 추가
  src/apis/auth/auth.ts
  src/apis/axiosInstance.ts
  src/apis/meetings/createOfflineMeeting.ts
  src/components/SignUp/ProfileImgStep.tsx
  src/components/common/Input/Input.stories.tsx
  src/components/event/BackgroundOption.tsx
  src/components/event/MeetingTimeOption.tsx
  src/components/event/TimePicker.tsx
  src/components/event/WheelPicker.tsx
  src/constants/MeetingFields.ts
  src/hooks/useTimePicker.ts
  src/hooks/useUserGender.ts
  src/pages/event/OfflineMeetingCreate.tsx
  src/pages/signup/LoginCallback.tsx
  src/styles/event/MeetingCreate.styled.ts
  src/styles/event/TimePicker.styled.ts
  src/types/svg.d.ts
  src/utils/dateUtils.ts
Labels: ♻Refactor

#38 #36 Feat: 마이페이지 UI 구현
  src/assets/images/ic_arrow_down.svg
  src/assets/images/ic_edit_camera.svg
  src/assets/images/ic_edit_profile.svg
  src/assets/images/ic_my_block.svg
  src/assets/images/ic_my_check.svg
  src/assets/images/ic_my_create.svg
  src/assets/images/ic_my_faq.svg
  src/assets/images/ic_my_notice.svg
  src/assets/images/ic_my_participate.svg
  src/assets/images/ic_my_pin.svg
  src/assets/images/ic_my_profile.svg
  src/assets/images/ic_my_search.svg
  src/components/common/Header/styles.ts
  src/components/common/Input/styles.ts
  src/constants/faqConstants.ts
  src/constants/mypageMenuConstants.ts
  src/pages/event/DeliveryMeetingCreate.tsx
  src/pages/mypage/BlockedUser.tsx
  src/pages/mypage/FAQ.tsx
  src/pages/mypage/MyCreatedMeetings.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/MyParticipatedMeetings.tsx
  src/pages/mypage/Notice.tsx
  src/pages/mypage/ReportedUser.tsx
  src/pages/mypage/UserInfoEdit.tsx
  src/routes/route.tsx
  src/styles/mypage/mypage.styled.ts
  src/styles/mypage/userInfoEdit.styled.ts
  src/styles/theme.ts
Labels: ✨Feature, 🎨Design

#45 #42 Refactor: 회원가입 api 연결 수정
  src/apis/auth/auth.ts
  src/apis/axiosInstance.ts
  src/components/SignUp/MbtiStep.tsx
  src/components/common/AuthGuard.tsx
  src/components/common/Loading.tsx
  src/pages/signup/LoginCallback.tsx
  src/pages/signup/SignupSuccess.tsx
  src/recoil/atoms/userAtom.tsx
  src/routes/route.tsx
  src/styles/SignUp/IntroPage.styled.ts
Labels: ♻Refactor, 🔗API

#43 #33 Feat: 홈 api 연결
  src/apis/meetings/getMeeting.ts
  src/components/Home/DeliveryCategory.tsx
  src/components/Home/MeetingList.tsx
  src/components/Home/MeetingListItem.tsx
  src/components/MeetingDetail/MeetingInfo.tsx
  src/components/event/MenuCategoryOption.tsx
  src/constants/deliveryItems.ts
  src/pages/Home.tsx
  src/pages/MeetingDetail.tsx
  src/pages/event/DeliveryMeetingCreate.tsx
  src/utils/dateUtils.ts
Labels: 🐞BugFix, ✨Feature, 🔧Chore, ♻Refactor, 🔗API

#47 #23 Feat: 배달팟 모임 생성 api 연결
  src/apis/meetings/createMeeting.ts
  src/assets/images/bank/ic_bank_hana.svg
  src/assets/images/bank/ic_bank_ibk.svg
  src/assets/images/bank/ic_bank_kakao.svg
  src/assets/images/bank/ic_bank_kookmin.svg
  src/assets/images/bank/ic_bank_mg.svg
  src/assets/images/bank/ic_bank_nh.svg
  src/assets/images/bank/ic_bank_shinhan.svg
  src/assets/images/bank/ic_bank_toss.svg
  src/assets/images/bank/ic_bank_woori.svg
  src/components/common/Input/Input.tsx
  src/components/common/Input/styles.ts
  src/components/common/Modal/BankSelectModal.tsx
  src/components/event/BackgroundOption.tsx
  src/components/event/MenuCategoryOption.tsx
  src/constants/MeetingFieldsConstants.ts
  src/constants/bankConstants.ts
  src/pages/event/DeliveryMeetingCreate.tsx
  src/pages/event/OfflineMeetingCreate.tsx
  src/pages/mypage/UserInfoEdit.tsx
  src/utils/dateUtils.ts
Labels: ✨Feature, 🎨Design, ♻Refactor, 🔗API

#50 #48 Fix: 오프라인 모임 생성 약속시간 수정
  src/apis/profile/getProfile.ts
  src/apis/profile/patchProfile.ts
  src/components/common/Input/Input.tsx
  src/hooks/useTimePicker.ts
  src/pages/event/OfflineMeetingCreate.tsx
  src/pages/mypage/MyPage.tsx
  src/pages/mypage/UserInfoEdit.tsx
Labels: 🐞BugFix, ♻Refactor
